name: LandBrush
version: 1.2.2
description: A smart plugin that makes creating new land easy.
author: LeonBlade
main: me.leonblade.landbrush.LandBrush
commands:
    landbrush:
        description: The base of all commands for landbrush
        permissions: landbrush
        usage: /<command> <func> [<arg0> ... <argX>]   